#ifndef KEYBOARD_HANDLER
#define KEYBOARD_HANDLER

#define KEYBOARD_BUFFER_SIZE 256
#define INPUT_BUFFER_SIZE 1024
#define KEYBOARD_SIZE 512
#define ASCII_MAP_SIZE 256
#define KEYBOARD_DATA 0x60
#define KEYBOARD_COMMAND 0x64
#include <stdint.h>
#include <stdbool.h>



typedef enum{
    KEY_NONE = 0,
    KEY_A, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, KEY_H, KEY_I, KEY_J, KEY_K, KEY_L, KEY_M, KEY_N, KEY_O, KEY_P, KEY_Q, KEY_R, KEY_S, KEY_T, KEY_U, KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z,
    KEY_BACK_TICK, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_MINUS, KEY_EQUALS,
    KEY_OPEN_BRACKET, KEY_CLOSE_BRACKET, KEY_BACKSLASH, KEY_SEMICOLON, KEY_APOSTROPHE, KEY_COMMA, KEY_PERIOD, KEY_SLASH,
    KEY_ESC, KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12, KEY_HOME, KEY_END, KEY_INSERT, KEY_DELETE,
    KEY_BACKSPACE, KEY_ENTER, KEY_LEFT_SHIFT, KEY_RIGHT_SHIFT, KEY_CAPSLOCK, KEY_TAB, KEY_FN, KEY_LEFT_CTRL, KEY_RIGHT_CTRL, KEY_LEFT_ALT, KEY_RIGHT_ALT, KEY_NUMBER_LOCK, KEY_PRNTSCRN, KEY_PGUP, KEY_PGDN, 
    KEYPAD_1, KEYPAD_2, KEYPAD_3, KEYPAD_4, KEYPAD_5, KEYPAD_6, KEYPAD_7, KEYPAD_8, KEYPAD_9, KEYPAD_0, KEYPAD_PLUS, KEYPAD_MINUS, KEYPAD_DIV, KEYPAD_MUL, KEYPAD_DEC,
    CURSOR_UP, CURSOR_DOWN, CURSOR_LEFT, CURSOR_RIGHT, KEY_SPACE, KEY_SCROLL_LOCK,
    KEY_WWW_SEARCH, KEY_PREV_TRACK, KEY_WWW_REFRESH, KEY_VOL_DOWN, KEY_VOL_UP, KEY_MUTE, KEY_WWW_FAVORITES, KEY_LEFT_GUI, KEY_RIGHT_GUI, KEY_WWW_STOP, KEY_CALCULATOR, KEY_APPS, KEY_WWW_FORWARD, KEY_WWW_BACK, KEY_PLAY_PAUSE, KEY_ACPI_POWER, KEY_STOP, KEY_ACPI_SLEEP,
    KEY_MY_COMPUTER, KEY_EMAIL, KEY_NEXT_TRACK, KEY_MEDIA_SELECT, KEY_ACPI_WAKE, KEY_PAUSE
} Keycode;


typedef struct{
    Keycode keycode;
    bool pressed;
    bool shift;
    bool capslock;
    bool ctrl;
    bool alt;
    bool numlock;
    bool new;
}KeyEvent;

#define EVENT_BUFFER_SIZE 256
void write_to_buffer_wrapper();
void write_to_buffer();
uint8_t switch_scancode_set(uint8_t set);
void disable_translation();
void read_from_buffer();
void push_keyevent(Keycode code, bool pressed);
#endif